# Generated by Django 4.0 on 2025-11-27 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_accounts', '0001_initial'),
        ('operator_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_info', models.CharField(help_text='イベント名', max_length=30)),
                ('event_overview', models.CharField(blank=True, help_text='イベント概要', max_length=100)),
                ('venue', models.CharField(help_text='開催場所', max_length=100)),
                ('start_date', models.DateTimeField(help_text='イベントの開始日（日時）')),
                ('end_date', models.DateTimeField(help_text='イベントの終了日（日時）')),
                ('start_time', models.DateTimeField(help_text='イベントの開始時間（日時）')),
                ('end_time', models.DateTimeField(help_text='イベントの終了時間（日時）')),
                ('public_settings', models.BooleanField(blank=True, default=False, help_text='公開設定（0:非公開, 1:公開）')),
                ('admin', models.ForeignKey(blank=True, db_column='admin', help_text='登録を行った管理者', on_delete=django.db.models.deletion.CASCADE, to='admin_accounts.admin')),
                ('operoter', models.ForeignKey(blank=True, db_column='operoter', help_text='イベントを主催する運営', on_delete=django.db.models.deletion.CASCADE, to='operator_accounts.operator')),
            ],
            options={
                'db_table': 'event_info',
            },
        ),
    ]
