# Generated by Django 4.0 on 2026-01-23 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_accounts', '0001_initial'),
        ('operator_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_info', models.CharField(help_text='イベント名', max_length=30)),
                ('event_overview', models.CharField(blank=True, help_text='イベント概要', max_length=100)),
                ('venue', models.CharField(help_text='開催場所', max_length=100)),
                ('start_date', models.DateField(help_text='開始日')),
                ('end_date', models.DateField(help_text='終了日')),
                ('start_time', models.TimeField(help_text='開始時間')),
                ('end_time', models.TimeField(help_text='終了時間')),
                ('public_settings', models.BooleanField(default=False, help_text='公開設定')),
                ('operator', models.ForeignKey(db_column='operator', on_delete=django.db.models.deletion.CASCADE, related_name='operator_events', to='operator_accounts.operator')),
            ],
            options={
                'db_table': 'operator_event_info',
            },
        ),
        migrations.CreateModel(
            name='AdminEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_info', models.CharField(help_text='イベント名', max_length=30)),
                ('event_overview', models.CharField(blank=True, help_text='イベント概要', max_length=100)),
                ('venue', models.CharField(help_text='開催場所', max_length=100)),
                ('start_date', models.DateField(help_text='開始日')),
                ('end_date', models.DateField(help_text='終了日')),
                ('start_time', models.TimeField(help_text='開始時間')),
                ('end_time', models.TimeField(help_text='終了時間')),
                ('public_settings', models.BooleanField(default=False, help_text='公開設定')),
                ('admin', models.ForeignKey(db_column='admin', on_delete=django.db.models.deletion.CASCADE, related_name='admin_events', to='admin_accounts.admin')),
            ],
            options={
                'db_table': 'admin_event_info',
            },
        ),
    ]
