# Generated by Django 4.0 on 2026-01-23 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operator_oshiro_info', '0001_initial'),
        ('admin_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='音声ガイドのタイトル', max_length=100)),
                ('guide_explanation', models.TextField(blank=True, help_text='ガイド内容の説明')),
                ('admin', models.ForeignKey(db_column='admin', help_text='登録した管理者', on_delete=django.db.models.deletion.CASCADE, to='admin_accounts.admin')),
                ('oshiro_info', models.ForeignKey(db_column='oshiro_info', help_text='対象のお城情報', on_delete=django.db.models.deletion.CASCADE, to='operator_oshiro_info.oshiroinfo')),
            ],
            options={
                'db_table': 'audio_guide',
            },
        ),
    ]
