@startuml 管理者がお城の周辺情報の登録をする


' ========================================
' 登場モノの定義
' ========================================
actor "管理者" as Admin
boundary "周辺ＭＡＰ機能画面" as b1
control "表示" as c1
boundary "周辺ＭＡＰ登録画面" as b2
control "処理" as c2
boundary "周辺ＭＡＰ登録完了画面" as b3
entity "周辺ＭＡＰ情報" as e1

' ========================================
' シーケンスの流れ
' ========================================

c1 -> b1 : 表示する():method=GET()
Admin -> b1 : 「新規登録」ボタンを押下する
b1 -> b2 : 表示する():method=GET()
Admin -> b2 : 必要なピンをマップ上に配置し、「登録」ボタンを押下する
b2 -> c2 : 起動する:method=POST()

alt 必要なピンをマップ上に配置していない場合
    c2 -> b2 : 「ピンをマップ上に配置してください」と\n赤文字でメッセージを画面に表示する
else 必要なピンをマップ上に配置されている場合
    c2 -> e1 : 登録する():boolean
    e1 --> c2
    c2 -> b3: 表示する():method=GET()
end

@enduml