@startuml 管理者がお城スタンプの更新をする


' ========================================
' 登場モノの定義
' ========================================
actor "管理者" as Admin
boundary "お城スタンプ一覧画面" as b1
control "表示" as c1
boundary "お城スタンプ更新画面" as b2
control "処理" as c2
boundary "お城スタンプ更新完了画面" as b3
entity "お城スタンプ情報" as e1

' ========================================
' シーケンスの流れ
' ========================================

c1 -> b1 : 表示する():method=GET()
Admin -> b1 : 更新したお城の「更新」ボタンを押下する
b1 -> b2 : 表示する:method=GET()

Admin -> b2 : 必要情報を入力しボタンを押下する

alt 「戻る」ボタンを押下した場合
    b2 -> b1 : 表示する():method=GET()

else 「更新」ボタンを押下した場合
    b2 -> c2 : 起動する:method=POST()

    alt お城スタンプ名が未入力の場合
        c2 -> b2 : 「このフィールドを入力してください」と\nメッセージを画面に表示する
    else お城スタンプ画像が未選択の場合
        c2 -> b2 : 「スタンプ画像を選択してください」と\n赤文字でメッセージを画面に表示する
    else すべて選択されている場合
        c2 -> e1 : 更新する():boolean
        e1 --> c2
        c2 -> b3 : 表示する : method=GET()

    end
end




@enduml