@startuml 利用者がアカウントを作成する  


' ========================================
' 登場モノの定義
' ========================================
actor "利用者" as User
boundary "アカウント作成画面" as b1
control "表示" as c1
control "処理" as c2
control "処理" as c3
boundary "ログイン画面" as b2
entity "アカウント" as e1

' ========================================
' シーケンスの流れ
' ========================================

c1 -> b1 : 表示する():method=GET()
User -> b1 : 必要情報を入力し、「Signup」ボタンを押下する
b1 -> c2 : 起動する:method=GET()
alt 「アカウント名」「Email」「Pass」が未入力の場合
    c2 -> b1 :「○○が入力されていません」と赤文字でメッセージを画面に表示する
else 「アカウント名」「Email」「Pass」が入力されている場合
    c2 -> c3 : 起動する:method=GET()
    alt 「Email」が既に使用済みの場合
        c3 -> b1 :「Emailが既に使用されています」と赤文字でメッセージを画面に表示する
    else 「Email」が使用済みでないの場合
        c3 -> e1 : 登録する():boolean
        e1 --> c3
        c3 -> b2 : 表示する():method=GET()
    end
end

@enduml