@startuml 利用者が音声ガイドを再生する


' ========================================
' 登場モノの定義
' ========================================
actor "利用者" as User
boundary "音声ガイドお城選択画面" as b1
control "表示" as c1
boundary "音声ガイドリスト画面" as b2
control "処理" as c2
control "処理" as c3
entity "音声ガイド" as e1

' ========================================
' シーケンスの流れ
' ========================================
c1 -> b1   : 表示する():method=GET()
User -> b1 : 「音声ガイドを聞く」ボタンを押下する
b1 -> b2 :表示する():method=GET()
b2 -> e1 : 参照する():method=GET()
e1 -->  b2 :
alt 音声ガイドが存在する場合
    b2 -> b2 : 「ガイドはまだ登録されていません。」メッセージを表示する
else 音声ガイドが存在する場合
    User -> b2 : 聞きたい音声ガイドの「音声ガイドを生成する」ボタンを押下する
    b2 -> c2 : 起動する():method=POST()
    c2 -> e1 : 参照する():method=POST()
    e1 --> c2 :
    c2 --> b2 :　生成する():method=POST()
    User -> b2 : 「▶（再生）」ボタンを押下する
    b2 -> c3 : 音声ガイドを再生する():method=GET()
    c3 --> b2


end



@enduml