# Generated by Django 4.0 on 2025-11-27 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_accounts', '0001_initial'),
        ('operator_oshiro_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_course_name', models.CharField(help_text='モデルコース名', max_length=30)),
                ('distance', models.FloatField(help_text='コースの距離')),
                ('required_time', models.TimeField(help_text='コースの所要時間')),
                ('course_overview', models.TextField(blank=True, help_text='コース概要')),
                ('difficulty', models.CharField(help_text='難易度（文字列）', max_length=20)),
                ('five_star_review', models.FloatField(help_text='評価（5段階などの数値）')),
                ('admin', models.ForeignKey(db_column='admin', help_text='モデルコースを登録した管理者', on_delete=django.db.models.deletion.CASCADE, to='admin_accounts.admin')),
                ('oshiro_info', models.ForeignKey(db_column='oshiro_info', help_text='対象のお城情報', on_delete=django.db.models.deletion.CASCADE, to='operator_oshiro_info.oshiroinfo')),
            ],
            options={
                'db_table': 'model_course',
            },
        ),
    ]
