# Generated by Django 4.0 on 2026-01-19 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_accounts', '0001_initial'),
        ('operator_oshiro_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_course_name', models.CharField(help_text='モデルコース名', max_length=30)),
                ('distance', models.FloatField(help_text='コースの距離')),
                ('required_time', models.TimeField(help_text='コースの所要時間')),
                ('course_overview', models.TextField(blank=True, help_text='コース概要')),
                ('difficulty', models.CharField(help_text='難易度（文字列）', max_length=20)),
                ('five_star_review', models.FloatField(default=0, help_text='評価（5段階などの数値）')),
                ('spot1_name', models.CharField(blank=True, help_text='スポット1名称', max_length=100, null=True)),
                ('spot1_short', models.TextField(blank=True, help_text='スポット1短い説明', null=True)),
                ('spot1_detail', models.TextField(blank=True, help_text='スポット1詳細', null=True)),
                ('spot1_image', models.ImageField(blank=True, help_text='スポット1画像', null=True, upload_to='model_course_spots/')),
                ('spot1_note', models.TextField(blank=True, help_text='スポット1補足', null=True)),
                ('spot2_name', models.CharField(blank=True, help_text='スポット2名称', max_length=100, null=True)),
                ('spot2_short', models.TextField(blank=True, help_text='スポット2短い説明', null=True)),
                ('spot2_detail', models.TextField(blank=True, help_text='スポット2詳細', null=True)),
                ('spot2_image', models.ImageField(blank=True, help_text='スポット2画像', null=True, upload_to='model_course_spots/')),
                ('spot2_note', models.TextField(blank=True, help_text='スポット2補足', null=True)),
                ('admin', models.ForeignKey(db_column='admin', help_text='モデルコースを登録した管理者', on_delete=django.db.models.deletion.CASCADE, to='admin_accounts.admin')),
                ('oshiro_info', models.ForeignKey(db_column='oshiro_info', help_text='対象のお城情報', on_delete=django.db.models.deletion.CASCADE, to='operator_oshiro_info.oshiroinfo')),
            ],
            options={
                'db_table': 'model_course',
            },
        ),
    ]
