# Generated by Django 4.0 on 2026-01-23 02:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('operator_oshiro_info', '0001_initial'),
        ('admin_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_course_name', models.CharField(help_text='モデルコース名', max_length=30)),
                ('distance', models.FloatField(help_text='コースの距離')),
                ('required_time', models.TimeField(help_text='コースの所要時間')),
                ('course_overview', models.TextField(blank=True, help_text='コース概要')),
                ('difficulty', models.CharField(help_text='難易度（文字列）', max_length=20)),
                ('five_star_review', models.FloatField(default=0, help_text='評価（5段階などの数値）')),
                ('admin', models.ForeignKey(db_column='admin', help_text='モデルコースを登録した管理者', on_delete=django.db.models.deletion.CASCADE, to='admin_accounts.admin')),
                ('oshiro_info', models.ForeignKey(db_column='oshiro_info', help_text='対象のお城情報', on_delete=django.db.models.deletion.CASCADE, to='operator_oshiro_info.oshiroinfo')),
            ],
            options={
                'db_table': 'model_course',
            },
        ),
        migrations.CreateModel(
            name='ModelCourseSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='表示順序')),
                ('name', models.CharField(blank=True, help_text='スポット名称', max_length=100, null=True)),
                ('short_description', models.TextField(blank=True, help_text='スポット短い説明', null=True)),
                ('detail', models.TextField(blank=True, help_text='スポット詳細', null=True)),
                ('image', models.ImageField(blank=True, help_text='スポット画像', null=True, upload_to='model_course_spots/')),
                ('note', models.TextField(blank=True, help_text='スポット補足', null=True)),
                ('model_course', models.ForeignKey(help_text='紐づくモデルコース', on_delete=django.db.models.deletion.CASCADE, related_name='spots', to='admin_model_course.modelcourse')),
            ],
            options={
                'db_table': 'model_course_spot',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='評価（1〜5）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='admin_model_course.modelcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
            options={
                'db_table': 'course_review',
                'unique_together': {('model_course', 'user')},
            },
        ),
    ]
