# Generated by Django 4.0 on 2026-01-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OshiroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oshiro_name', models.CharField(help_text='お城名', max_length=50)),
                ('oshiro_images', models.ImageField(help_text='お城の代表画像', upload_to='oshiro_images/')),
                ('address', models.CharField(help_text='住所', max_length=100)),
                ('built_year', models.IntegerField(help_text='築城年（西暦など）')),
                ('structure', models.TextField(blank=True, help_text='お城の構造の説明')),
                ('ruins', models.TextField(blank=True, help_text='遺構の説明', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='お城中心の緯度（周辺MAPの初期表示に使用）', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='お城中心の経度（周辺MAPの初期表示に使用）', null=True)),
            ],
            options={
                'db_table': 'oshiro_info',
            },
        ),
    ]
