@startuml 運営がお城情報の更新をする


' ========================================
' 登場モノの定義
' ========================================
actor "運営" as Operator
boundary "お城情報一覧画面" as b1
control "表示" as c1
boundary "お城情報更新画面" as b2
control "処理" as c2
boundary "お城情報更新完了画面" as b3
entity "お城情報" as e1

' ========================================
' シーケンスの流れ
' ========================================

c1 -> b1 : 表示する():method=GET()
Operator -> b1 : 「更新」ボタンを押下する
b1 -> b2 : 表示する():method=GET()
Operator -> b2 : 必要情報を入力し、「更新」ボタンを押下する
b2 -> c2 : 起動する:method=POST()

alt 必要情報が未入力の場合
    c2 -> b2 : エラーメッセージを表示する
else 必要情報が入力されている場合
    c2 -> e1 : 更新する():boolean
    e1 --> c2
    c2 -> b3: 表示する():method=GET()
end

@enduml