# Generated by Django 4.0 on 2026-01-21 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operator_oshiro_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.IntegerField(help_text='入場料')),
                ('business_opening_hours', models.TimeField(help_text='営業開始時間')),
                ('business_closing_hours', models.TimeField(help_text='営業終了時間')),
                ('access_info', models.TextField(help_text='アクセス情報')),
                ('highlights_img', models.ImageField(blank=True, help_text='見どころ画像', upload_to='highlights/')),
                ('highlights', models.TextField(blank=True, help_text='見どころ説明')),
                ('gojoin_stamp', models.ImageField(blank=True, help_text='御城印画像', null=True, upload_to='gojoin_stamp/')),
                ('gojoin', models.TextField(blank=True, help_text='御城印説明', null=True)),
                ('oshiro_info', models.OneToOneField(db_column='oshiro_info', help_text='対象のお城情報', on_delete=django.db.models.deletion.CASCADE, to='operator_oshiro_info.oshiroinfo')),
            ],
            options={
                'db_table': 'basic_info',
            },
        ),
    ]
