@startuml 利用者がモデルコースを検索する


' ========================================
' 登場モノの定義
' ========================================
actor "利用者" as user
boundary "モデルコース画面" as b1
control "表示" as c1
control "処理" as c2
boundary "モデルコース検索画面" as b2
boundary "モデルコース（詳細）画面" as b3
entity "モデルコース" as e1
' ========================================
' シーケンスの流れ
' ========================================
c1 -> b1 : 表示する():method=GET()
user -> b1 : お城を選択し「検索」ボタンを押下する
b1 -> c2 : 起動する():method=POST()
c2 -> e1 : 参照する()
c2 <-- e1
alt 未選択だった場合
    c2 -> b2 : 表示する():method=GET()
    b2 -> b1 : 表示する():method=GET()
else 選択されていた場合
    c2 -> b2 : 表示する():method=GET()
    user -> b2 : 「詳細を見る」ボタンを押下する
    b2 -> b3 : 表示する()method=GET()
end


