# Generated by Django 4.0 on 2026-01-21 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('operator_oshiro_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('account', models.OneToOneField(help_text='管理者としてのアカウント', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_profile', serialize=False, to='accounts.account')),
                ('oshiro_management1', models.ForeignKey(blank=True, help_text='管理するお城1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_slot1', to='operator_oshiro_info.oshiroinfo')),
                ('oshiro_management2', models.ForeignKey(blank=True, help_text='管理するお城2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_slot2', to='operator_oshiro_info.oshiroinfo')),
                ('oshiro_management3', models.ForeignKey(blank=True, help_text='管理するお城3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_slot3', to='operator_oshiro_info.oshiroinfo')),
                ('oshiro_management4', models.ForeignKey(blank=True, help_text='管理するお城4', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_slot4', to='operator_oshiro_info.oshiroinfo')),
                ('oshiro_management5', models.ForeignKey(blank=True, help_text='管理するお城5', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_slot5', to='operator_oshiro_info.oshiroinfo')),
            ],
            options={
                'verbose_name': '管理者',
                'verbose_name_plural': '管理者',
                'db_table': 'admin',
            },
        ),
    ]
