# Generated by Django 4.0 on 2026-01-21 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_basic_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMapInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(help_text='アイコン名（例：トイレ・駐車場）', max_length=20)),
                ('icon_image', models.ImageField(blank=True, help_text='未選択ならカテゴリ既定アイコンを表示', null=True, upload_to='area_map_icons/')),
                ('latitude', models.FloatField(help_text='緯度')),
                ('longitude', models.FloatField(help_text='経度')),
                ('basic_info', models.ForeignKey(db_column='basic_info', help_text='紐づく基本情報（どのお城のMAPか）', on_delete=django.db.models.deletion.CASCADE, to='admin_basic_info.basicinfo')),
            ],
            options={
                'db_table': 'area_map_info',
            },
        ),
    ]
