@startuml 利用者が口コミを削除する


' ========================================
' 登場モノの定義
' ========================================
actor "利用者" as User
boundary "お城リスト画面" as b1
control "表示" as c1
boundary "口コミ画面" as b2
control "処理" as c2
control "処理" as c3
entity "口コミ" as e1

' ========================================
' シーケンスの流れ
' ========================================
c1 -> b1   : 表示する():method=GET()
User -> b1 : 「口コミ」ボタンを押下する
b1 -> b2   : 表示する:method=GET()

User -> b2 : 「削除」ボタンを押下する
b2 -> e1   : 参照する()
b2 <-- e1

User -> b2 : ボタンを押下する
b2 -> c2   : 起動する():method=GET()


alt 「戻る」ボタンが押下された場合
    b2 -> b2 : 表示する():method=GET()

else 「削除」ボタンが押下された場合
    c2 -> c3   : 起動する():method=POST()
    c3 ->  e1 :  削除する():boolean
    c3 <-- e1
    c3 -> b2 : 表示する():method=GET()
        
end



@enduml