@startuml 利用者が口コミを投稿する


' ========================================
' 登場モノの定義
' ========================================
actor "利用者" as User
boundary "お城リスト画面" as b1
control "表示" as c1
boundary "口コミ画面" as b2
control "処理" as c2
entity "口コミ" as e1

' ========================================
' シーケンスの流れ
' ========================================
c1 -> b1   : 表示する():method=GET()
User -> b1 : 「口コミ」ボタンを押下する
b1 -> b2   : 表示する:method=GET()
b2 -> e1   : 参照する()
b2 <-- e1
User -> b2 : 必要情報を入力し、「投稿」ボタンを押下する

b2 -> c2   : 起動する():method=POST()

alt 「タイトル」が未入力の場合
    c2 -> b1 : 「タイトルが未入力です」と赤文字でメッセージを画面に表示する

else 「コメント」が未入力の場合
    c2 -> b1 : 「コメントが未入力です」と赤文字でメッセージを画面に表示する

else 「評価」が未入力の場合
    c2 -> b1 : 「評価が未入力です」と赤文字でメッセージを画面に表示する

else 入力が正しい場合
    c2 ->  e1 : 登録する():boolean
    c2 <-- e1
    c2 -> b2 : 表示する():method=GET()
        
end



@enduml