# Generated by Django 4.0 on 2026-01-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
        ('admin_accounts', '0001_initial'),
        ('operator_oshiro_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OshiroStampInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oshiro_stamp_image', models.ImageField(help_text='お城スタンプ画像', upload_to='oshiro_stamp_images/')),
                ('stamp_name', models.CharField(help_text='スタンプ名', max_length=20)),
                ('admin', models.ForeignKey(db_column='admin', help_text='登録した管理者', on_delete=django.db.models.deletion.CASCADE, to='admin_accounts.admin')),
                ('oshiro_info', models.OneToOneField(db_column='oshiro_info', help_text='対象のお城情報（1対1）', on_delete=django.db.models.deletion.CASCADE, to='operator_oshiro_info.oshiroinfo')),
            ],
            options={
                'db_table': 'oshiro_stamp_info',
            },
        ),
        migrations.CreateModel(
            name='OshiroStamp',
            fields=[
                ('oshiro_stamp_info', models.OneToOneField(db_column='oshiro_stamp_info', help_text='対象のお城スタンプ情報（主キー）', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_oshiro_stamp.oshirostampinfo')),
                ('oshiro_stamp', models.IntegerField(help_text='お城スタンプ数')),
                ('date', models.DateField(help_text='スタンプ取得日')),
                ('user', models.ForeignKey(db_column='user', help_text='スタンプを持っている利用者', on_delete=django.db.models.deletion.CASCADE, to='user_accounts.user')),
            ],
            options={
                'db_table': 'oshiro_stamp',
            },
        ),
    ]
