@startuml お城_クラス図

skinparam classAttributeIconSize 0
' ========================================
' クラス図の定義
' ========================================

class "お城情報"{
    - お城名:Char
    - お城画像:img
    - 住所:Char
    - 築城年:int
    - 構造:text
    - 遺構:text
    + 登録する()
    + 更新する()
}

class "イベント情報"{
    - イベント名:Char
    - イベント概要:Char
    - 開催場所:Char
    - 開始日:DateTime
    - 終了日:DateTime
    - 開始時間:Time
    - 終了時間:Time
    - 公開設定:boolean
    + 登録する()
    + 更新する()
    + 削除する()
}




class "音声ガイド"{
    - お城情報:FK
    - タイトル:Char
    - ガイド説明:text
    - QR:img
    + 登録する()
    + 更新する()
    + 削除する()
}


class "周辺MAP情報"{
    - 基本情報:FK
    - アイコン名 : Char
    - アイコン画像 : img
    - 緯度 : float
    - 経度 : float
    + 登録する()
    + 更新する()
    + 削除する()
}

class "基本情報"{
    - お城情報:One to One
    - 入場料:int
    - 営業開始時間:Time
    - 営業終了時間:Time
    - アクセス情報:text
    - 見どころ画像:img
    - 見どころ説明:text
    - 御城印画像:img
    - 御城印説明:text
    - 周辺MAP:map
    + 更新する()
}



class "アカウント"{
    - Email:email
    - ID:Char:PK
    - Pass:password
    - アカウント名:Char
}

class "利用者"{

    - アカウント:One to One
    - プロフィール画像:img
    - 自己紹介:text
}

class "お城マイリスト"{
    - 利用者:FK
    - お城情報:FK
    + 追加する()
    + 削除する()
}

class "管理者"{
    - アカウント:One to One
    - 管理するお城1:お城情報:FK
    - 管理するお城2:お城情報:FK
    - 管理するお城3:お城情報:FK
    - 管理するお城4:お城情報:FK
    - 管理するお城5:お城情報:FK
}

class "運営"{
    - アカウント:One to One
}

class "口コミ"{
    - 利用者:FK
    - タイトル:Char
    - コメント:text
    - 写真:img
    - 評価:float
    - 投稿日時:DateTime
    + 投稿する()
    + 更新する()
    + 削除する()
}


class "お城スタンプ情報"{
    - お城情報:One to One
    - 管理者:FK
    - お城スタンプ画像:img
    - スタンプ名:Char
    + 登録する()
}

class "モデルコース"{
    - お城情報:FK
    - モデルコース名:Char
    - 距離:float
    - 所要時間:Time
    - コース概要:text
    - 難易度:Char
    - 評価:float
    + 登録する()
    + 更新する()
}


class "お城スタンプ"{
    - お城スタンプ情報:FK
    - 利用者:FK
    - お城スタンプ数:int
    - 日付:Date
    + 登録する()
}



' ========================================
' クラス間の関連付け
' ========================================

アカウント "1" - "1" 利用者
アカウント "1" -- "1" 管理者
アカウント "1" -- "1" 運営
管理者 "1" -- "0..*" イベント情報
運営 "1" -- "0..*" イベント情報
利用者 "1" - "   0..*" 口コミ
利用者 "1" -- "0..*" お城マイリスト
利用者 "1" -- "0..*" お城スタンプ
お城情報 "1" - "0..*" お城マイリスト
お城スタンプ "0..*" -- "1" お城スタンプ情報
お城スタンプ情報 "1" -- "1" お城情報
運営 "1" -- "0..*" お城情報
管理者 "1" -- "1..*" お城情報
モデルコース "0..*" -- "1" お城情報
音声ガイド "0..*" -- "1" お城情報
周辺MAP情報 "0..*" -- "1" 基本情報
基本情報 "1" -- "1" お城情報


@enduml


