@startuml お城_クラス図

skinparam classAttributeIconSize 0
' ========================================
' クラス図の定義
' ========================================

class "アカウント"{
    - Email:email
    - ID:Char:PK
    - Pass:password
    - アカウント名:Char
}

class "管理者"{
    - アカウント:One to One
    - 管理するお城1:お城情報:FK
    - 管理するお城2:お城情報:FK
    - 管理するお城3:お城情報:FK
    - 管理するお城4:お城情報:FK
    - 管理するお城5:お城情報:FK
}

class "周辺MAP情報"{
    - 基本情報:FK
    - アイコン名 : Char
    - アイコン画像 : img
    - 緯度 : float
    - 経度 : float
    + 登録する()
    + 更新する()
    + 削除する()
}


class "音声ガイド"{
    - お城情報:FK
    - 管理者:FK
    - タイトル:Char
    - ガイド説明:text
    + 登録する()
    + 更新する()
    + 削除する()
}

class "基本情報"{
    - お城情報:One to One
    - 入場料:int
    - 営業開始時間:Time
    - 営業終了時間:Time
    - アクセス情報:text
    - 見どころ画像:img
    - 見どころ説明:text
    - 御城印画像:img
    - 御城印説明:text
    + 更新する()
}

class "モデルコース"{
    - お城情報:FK
    - 管理者:FK
    - モデルコース名:Char
    - 距離:float
    - 所要時間:Time
    - コース概要:text
    - 難易度:Char
    - 評価:float
    + 登録する()
    + 更新する()
}

class "モデルコーススポット"{
    - モデルコース:FK
    - 表示順序:int
    - スポット名:Char
    - スポット説明:text
    - スポット詳細:text
    - スポット画像:img
    - スポット補足:text
    + 登録する()
    + 更新する()
}

class "モデルコース評価"{
    - モデルコース:FK
    - 利用者:FK
    - 評価:float
    + 更新する()
}


class "お城スタンプ情報"{
    - お城情報:One to One
    - 管理者:FK
    - お城スタンプ画像:img
    - スタンプ名:Char
    + 登録する()
}



class "お城スタンプ"{
    - お城スタンプ情報:FK
    - 利用者:FK
    - スタンプ取得日:Date
    + 登録する()
}

class "イベント情報"{
    - イベント名:Char
    - イベント概要:Char
    - 開催場所:Char
    - 開始日:DateTime
    - 終了日:DateTime
    - 開始時間:Time
    - 終了時間:Time
    - 公開設定:boolean
    + 登録する()
    + 更新する()
    + 削除する()
}

class "運営イベント情報"{
    - イベント情報:FK
    - 運営:FK
}

class "管理者イベント情報"{
    - イベント情報:FK
    - 管理者:FK
}


class "運営"{
    - アカウント:One to One
}


class "お城情報"{
    - お城名:Char
    - お城画像:img
    - 住所:Char
    - 築城年:int
    - 構造:text
    - 遺構:text
    - 緯度 : float
    - 経度 : float
    + 登録する()
    + 更新する()
}


class "利用者"{

    - アカウント:One to One
    - プロフィール画像:img
    - 自己紹介:text
}

class "口コミ"{
    - 利用者:FK
    - お城情報:FK
    - タイトル:Char
    - コメント:text
    - 写真:img
    - 評価:float
    - 投稿日時:DateTime
    + 投稿する()
    + 更新する()
    + 削除する()
}


class "お城マイリスト"{
    - 利用者:FK
    - お城情報:FK
    + 追加する()
    + 削除する()
}



' ========================================
' クラス間の関連付け
' ========================================

アカウント "1" -- "1" 利用者
管理者 "1" -- "1" アカウント
アカウント "1" - "1" 運営
口コミ "多" -- "1" 利用者   
お城情報 "1" -- "多" 口コミ
お城情報 "1" -- "1" 管理者
お城情報 "1" -- "多" 音声ガイド
音声ガイド "1" -- "1" 管理者
基本情報 "1" -- "1" お城情報
お城情報 "1" -- "多" モデルコース
モデルコーススポット "多" -- "1" モデルコース
モデルコース "1" -- "1" 管理者
モデルコース "1" -- "多" モデルコース評価
利用者 "1" - "多" モデルコース評価
お城情報 "1" - "1" お城スタンプ情報
お城スタンプ情報 "1" -- 管理者
お城スタンプ情報 "1" -- "多" お城スタンプ
お城スタンプ "多" -- "1" 利用者
イベント情報 "多" -- "1" 運営イベント情報
イベント情報 "多" -- "1" 管理者イベント情報
運営イベント情報 "多" -- "1" 運営
管理者イベント情報 "多" -- "1" 管理者
周辺MAP情報 "1" - "1" 基本情報
お城情報 "1" -- "多" お城マイリスト
お城マイリスト "多" -- "1" 利用者

@enduml


