# Generated by Django 4.0 on 2026-01-21 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('operator_oshiro_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, help_text='プロフィール画像', null=True, upload_to='profile_images/')),
                ('user_about', models.TextField(blank=True, help_text='自己紹介文', null=True)),
                ('account', models.OneToOneField(help_text='紐づくアカウント（1アカウント = 1利用者）', on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='accounts.account')),
            ],
            options={
                'verbose_name': '利用者',
                'verbose_name_plural': '利用者',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(help_text='口コミタイトル', max_length=20)),
                ('review_comments', models.CharField(blank=True, help_text='口コミコメント', max_length=50)),
                ('review_image', models.ImageField(help_text='口コミに添付された画像', null=True, upload_to='review_images/')),
                ('five_star_review', models.FloatField(help_text='評価（数値・5段階など）')),
                ('post_date_time', models.DateTimeField(auto_now_add=True, help_text='口コミを投稿した日時')),
                ('oshiro_info', models.ForeignKey(db_column='oshiro_info', help_text='口コミしたお城', on_delete=django.db.models.deletion.CASCADE, to='operator_oshiro_info.oshiroinfo')),
                ('user', models.ForeignKey(db_column='user', help_text='口コミ投稿者（利用者）', on_delete=django.db.models.deletion.CASCADE, to='user_accounts.user')),
            ],
            options={
                'db_table': 'user_review',
            },
        ),
    ]
