@startuml 管理者がQRコードを生成する


' ========================================
' 登場モノの定義
' ========================================
actor "管理者" as admin
boundary "QRコード生成画面" as b1
control "表示" as c1
control "処理" as c2
control "処理" as c3

' ========================================
' シーケンスの流れ
' ========================================

c1 -> b1 : 表示する():method=GET()
admin -> b1 : 必要情報を入力し、ボタンを押下する
alt 「生成」ボタンを押下した場合
    b1 -> c2 : 起動する():method=POST()
    c2 --> b1 : 生成したQRコードを画面に表示する
else 「ダウンロード」ボタンを押下した場合
    b1 -> c3 : 起動する():method=GET()
    c3 --> b1 : QRコードをダウンロードする
end
@enduml
