@startuml 管理者が音声ガイドを登録する


' ========================================
' 登場モノの定義
' ========================================
actor "管理者" as admin
boundary "音声ガイド機能画面" as b1
control "表示" as c1
boundary "音声ガイド登録画面" as b2
control "処理" as c2
control "処理" as c3
entity "音声ガイド" as e1
boundary "音声ガイド登録完了画面" as b3
' ========================================
' シーケンスの流れ
' ========================================
c1 -> b1 : 表示する():method=GET()
admin -> b1 : 「音声ガイドを追加」ボタンを押下する
b1 -> b2 : 表示する():method=GET()
admin -> b2 : 必要事項を入力しボタンを押下する

alt 「戻る」ボタンを押下した場合
    b2 -> b1 : 表示する():method=GET()
else 「試し聞く」ボタンを押下した場合
    b2 -> c2 : 起動する():method=POST()
    alt 未入力の場合
        c2 -> b2 : システムは「未入力のものがあります」\nと赤文字で画面にメッセージを表示する
    else すべて入力されている場合
        c2 -> b2 : システムはガイド説明で\n入力した内容を再生する
    end
else 「登録」ボタンを押下した場合
    b2 -> c3 : 起動する():method=POST()
    alt 未入力の場合
        c3 -> b2 : システムは「未入力のものがあります」\nと赤文字で画面にメッセージを表示する
    else すべて入力されている場合
        c3 -> e1 : 登録する():boolean
        c3 <-- e1
        c3 -> b3 : 表示する():method=GET()
    end
end


