@startuml 管理者が音声ガイドを削除する


' ========================================
' 登場モノの定義
' ========================================
actor "管理者" as admin
boundary "音声ガイド機能画面" as b1
control "表示" as c1
boundary "音声ガイド削除確認画面" as b2
control "処理" as c2
entity "音声ガイド" as e1
boundary "音声ガイド削除完了画面" as b3
' ========================================
' シーケンスの流れ
' ========================================
c1 -> b1 : 表示する():method=GET()
admin -> b1 : 「削除」ボタンを押下する
b1 -> b2 : 表示する():method=GET()
admin -> b2 : ボタンを押下する

alt 「戻る」ボタンを押下した場合
    b2 -> b1 : 表示する():method=GET()
else 「削除」ボタンを押下した場合
    b2 -> c2 : 起動する():method=POST()
    c2 -> e1 :削除する():boolean
    c2 <-- e1
    c2 -> b3 : 表示する():method=GET()
end


