@startuml 管理者が音声ガイドを登録する


' ========================================
' 登場モノの定義
' ========================================
actor "管理者" as admin
boundary "音声ガイドお城一覧画面" as b0
control "表示" as c1
boundary "音声ガイド一覧画面" as b1
boundary "音声ガイド登録画面" as b2
control "処理" as c3
entity "お城情報" as e0
entity "音声ガイド" as e1
boundary "音声ガイド登録完了画面" as b3

' ========================================
' シーケンスの流れ
' ========================================

' b0（お城一覧）の表示に必要な参照
c1 -> e0 : 参照する()
c1 <-- e0
c1 -> b0 : 表示する():method=GET()

admin -> b0 : 「音声ガイド一覧・編集」ボタンを押下する

' b1（音声ガイド一覧）の表示に必要な参照（boundary→control→entity→boundary）
b0 -> c1 : 起動する():method=GET()
c1 -> e1 : 参照する()
c1 <-- e1
c1 -> b1 : 表示する():method=GET()

admin -> b1 : 「新規音声ガイド登録」ボタンを押下する

' b2（登録画面）の表示
b1 -> c1 : 起動する():method=GET()
c1 -> b2 : 表示する():method=GET()

admin -> b2 : 必要情報を入力し「登録」ボタンを押下する

alt 「戻る」ボタンを押下した場合
    b2 -> b1 : 表示する():method=GET()

else 「登録」ボタンを押下した場合
    b2 -> c3 : 起動する():method=POST()
    alt 未入力の場合
        c3 -> e1 : 参照する()
        c3 <-- e1
        c3 -> b2 : システムは「このフィールドを入力してください」\nとメッセージを画面に表示する
    else すべて入力されている場合
        c3 -> e1 : 登録する():boolean
        c3 <-- e1
        c3 -> b3 : 表示する():method=GET()
    end
    alt 「音声ガイド一覧へ戻る」ボタンを押下した場合
        c1 -> e1 : 参照する()
        c1 <-- e1
        b3 -> b1 : 表示する():method=GET()
    end
end

@enduml
