@startuml 管理者がモデルコースを更新する


' ========================================
' 登場モノの定義
' ========================================
actor "管理者" as admin
boundary "モデルコース機能画面" as b1
control "表示" as c1
boundary "モデルコース更新画面" as b2
control "処理" as c2
control "処理" as c3
entity "モデルコース" as e1
boundary "モデルコース更新完了完了画面" as b3
' ========================================
' シーケンスの流れ
' ========================================
c1 -> e1 : 参照する()
c1 <-- e1
c1 -> b1 : 表示する():method=GET()
admin -> b1 : 「更新」ボタンを押下する
b1 -> b2 : 起動する():method=GET()
admin -> b2 : 必要情報を入力しボタンを押下する

alt 「キャンセル」ボタンを押下した場合
    b2 -> b1 : 表示する():method=GET()
else 「スポット追加」ボタンを押下した場合
    b2 -> c2 : 起動する():method=GET()
    c2 -> b2 : 表示する():method=GET()
else 「更新」ボタンを押下した場合
    b2 -> c3 : 起動する():method=POST()
    alt 未入力の場合
        c3 -> b2 : 「必要情報を入力してください」と\n赤文字でメッセージを画面に表示する
    else すべて入力されている場合
        c3 -> e1 : 更新する():boolean
        c3 <-- e1 
        c3 -> b3 : 表示する():method=GET()
    end
end

