# Generated by Django 4.0 on 2026-01-21 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_accounts', '0001_initial'),
        ('operator_oshiro_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OshiroMyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oshiro_info', models.ForeignKey(db_column='oshiro_info', help_text='お気に入り登録されたお城', on_delete=django.db.models.deletion.CASCADE, to='operator_oshiro_info.oshiroinfo')),
                ('user', models.ForeignKey(db_column='user', help_text='マイリストを持つ利用者', on_delete=django.db.models.deletion.CASCADE, to='user_accounts.user')),
            ],
            options={
                'db_table': 'osiro_my_list',
            },
        ),
    ]
