@startuml 運営がログインをする


' ========================================
' 登場モノの定義
' ========================================
actor "運営" as User
boundary "ログイン画面" as b1
control "表示" as c1
control "処理" as c2
control "処理" as c3
boundary "Top画面" as b2
entity "アカウント" as e1

' ========================================
' シーケンスの流れ
' ========================================

c1 -> b1 : 表示する():method=GET()
User -> b1 : 必要情報を入力し、「Login」ボタンを押下する
b1 -> c2 : 起動する():method=POST()
alt 「Email」が未入力の場合
    c2 -> b1 : 「Emailが入力されていません」と赤文字でメッセージを画面に表示する
else 「Pass」が未入力の場合
    c2 -> b1 : 「Passが入力されていません」と赤文字でメッセージを画面に表示する
else 「Email」「Pass」が入力されている場合
    c2 -> e1 : 参照する()
    e1 --> c2 : 
    c2 -> c3 : 起動する():method=GET()
    alt 「Email」又は「Pass」が間違っている場合
        c3 -> b1 :「EmailまたはPassが間違っています」と赤文字でメッセージを画面に表示する
    else 「Email」と「Pass」が正しい場合
        c3 -> b2 : 表示する():method=GET()
    end
end

@enduml