@startuml 運営がログアウトをする


' ========================================
' 登場モノの定義
' ========================================
actor "運営" as User
boundary "ログアウト画面" as b1
control "表示" as c1
boundary "ログアウト完了画面" as b2


' ========================================
' シーケンスの流れ
' ========================================

c1 -> b1 : 表示する():method=GET()
User -> b1 :「ログアウト」ボタンを押下する
b1 -> b2 : 表示する():method=GET()

@enduml