@startuml 運営が管理者アカウントを作成する  


' ========================================
' 登場モノの定義
' ========================================
actor "運営" as Operator
boundary "管理者アカウント画面" as b1
control "表示" as c1
boundary "管理者アカウント登録画面" as b2
control "処理" as c2
boundary "管理者アカウント登録完了画面" as b3
entity "アカウント" as e1

' ========================================
' シーケンスの流れ
' ========================================

c1 -> b1 : 表示する():method=GET()
Operator -> b1 : 「新規登録」ボタンを押下する
b1 -> b2 : 表示する():method=GET()
Operator -> b2 : 必要情報を入力しボタンを押下する
alt 「キャンセル」ボタン押下した場合
    b2 -> b1 : 表示する():method=GET()
else 「登録」ボタン押下した場合
    b2 -> c2 : 起動する():method=POST()
    alt 「Email」が未入力の場合
        c2 -> b2 : 「Emailを入力してください」と\n赤文字でメッセージを画面に表示する
    else  「Pass」が未入力の場合
        c2 -> b2 : 「Passを入力してください」と\n赤文字でメッセージを画面に表示する
    else   「アカウント名」が未入力の場合
        c2 -> b2 : 「アカウント名を入力してください」と\n赤文字でメッセージを画面に表示する
    else 「管理するお城」が未入力の場合
        c2 -> b2 : 「管理するお城を入力してください」と\n赤文字でメッセージを画面に表示する
    else  すべて入力済の場合
        c2 -> e1 : 登録する():boolean
        c2 <-- e1
        c2 -> b3 : 表示する():method=GET()
    end
end




@enduml