@startuml 利用者がお城マイリストに追加する


' ========================================
' 登場モノの定義
' ========================================
actor "利用者" as User
boundary "マイページ画面" as b1
control "表示" as c1
boundary "お城マイリスト画面" as b2
control "処理" as c2
entity "お城マイリスト" as e1
' ========================================
' シーケンスの流れ
' ========================================
c1 -> b1   : 表示する():method=GET()
User -> b1 : 「お城マイリスト」ボタンを押下する
b1 -> b2   : 表示する:method=GET()

User -> b2 : お城を選択し、ボタンを押下する

alt 「マイページに戻る」ボタンを押下した場合
    b2 -> b1 : 表示する():method=GET()

    else お気に入りボタンを押下した場合
        b2 ->  e1 : 参照する()
        b2 <-- e1
        b2 -> c2   : 起動する():method=POST()
        

        alt 何も選択されていない場合
            c2 -> b2 : 「お城を選択して下さい」\nと赤文字でメッセージを画面に表示する
        else お城を選択していた場合
            c2 ->  e1 : 追加する():boolean
            c2 <-- e1
            c2 ->  b2 : 表示する():method=GET()
    end

end



@enduml