@startuml 利用者がプロフィールを更新する


' ========================================
' 登場モノの定義
' ========================================
actor "利用者" as User
boundary "マイページ画面" as b1
control "表示" as c1
boundary "プロフィール画面" as b2
control "処理" as c2
boundary "プロフィール更新完了画面" as b3
entity "利用者" as e1
' ========================================
' シーケンスの流れ
' ========================================
c1 -> b1   : 表示する():method=GET()
User -> b1 : 「プロフィール」ボタンを押下する
b1 -> b2   : 表示する:method=GET()

User -> b2 : 必須情報を入力し、ボタンを押下する

alt 「マイページに戻る」ボタンを押下した場合
    b2 -> b1 : 表示する():method=GET()

else 更新ボタンを押下した場合
    b2 ->  e1 : 参照する()
    b2 <-- e1
    b2 -> c2   : 起動する():method=POST()
        

    alt 「名前」が未入力の場合
        c2 -> b2 : 「名前を入力してください」と\n赤文字でメッセージを画面に表示する

    else 「自己紹介」が未入力の場合
        c2 -> b2 : 「自己紹介を入力してください」と\n赤文字でメッセージを画面に表示する


    else 入力済みの場合
        c2 ->  e1 : 更新する():boolean
        c2 <-- e1
        c2 ->  b3 : 表示する():method=GET()
    end

end



@enduml