@startuml 利用者がお城スタンプを登録する


' ========================================
' 登場モノの定義
' ========================================
actor "利用者" as User
boundary "マイページ画面" as b1
control "表示" as c1
boundary "お城スタンプ画面" as b2
control "処理" as c2
entity "お城スタンプ" as e1
' ========================================
' シーケンスの流れ
' ========================================
c1 -> b1   : 表示する():method=GET()
User -> b1 : 「お城スタンプ」ボタンを押下する
b1 -> b2   : 表示する:method=GET()

User -> b2 : ボタンを押下する


alt 「マイページに戻る」ボタンを押下した場合
    b2 -> b1 : 表示する():method=GET()

    else 「スタンプを登録する」ボタンを押下した場合
        b2 ->   e1 : 参照する()
        b2 <--  e1 
        b2 -> c2   : 起動する():method=POST()
        c2 ->  e1  : 登録する():boolean
        c2 <-- e1
        c2 -> b2   : 表示する():method=GET()

end



@enduml