@startuml 管理者がログアウトをする


' ========================================
' 登場モノの定義
' ========================================
actor "管理者" as Admin
boundary "ログアウト画面" as b1
control "表示" as c1
boundary "ログアウト確認画面" as b2
boundary "Top画面" as b3
boundary "ログイン画面" as b4


' ========================================
' シーケンスの流れ
' ========================================

c1 -> b1 : 表示する():method=GET()
Admin -> b1 :「ログアウト」ボタンを押下する
b1 -> b2 : 表示する():method=GET()
Admin -> b2 :　ボタンを押下する
alt 「戻る」ボタンを押下した場合
    b2 -> b3 : 表示する():method=GET()
else 「ログアウト」ボタンを押下した場合
    b2-> b4 : 表示する():method=GET()
end

@enduml