# Generated by Django 4.0 on 2026-01-21 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.OneToOneField(help_text='運営としてのアカウント', on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to='accounts.account')),
            ],
            options={
                'verbose_name': '運営',
                'verbose_name_plural': '運営',
                'db_table': 'operator',
            },
        ),
    ]
